### ISSUE TITLE
Bad hostname presented

### ISSUE THREAD

**Issue by nirvdrum** [laurilehmijoki/jekyll-s3#22]
Hi,

I just got started with jekyll-s3.  Everything worked quite well, except the generated URL doesn't quite work right.  In my case, the tool spit out:

http://blog.mogotest.com.s3.amazonaws.com/index.html

And that mostly works, but index documents fail.  As it turns out, there's a special S3 URL form that you need for everything to work right.  In my case:

http://blog.mogotest.com.s3-website-us-east-1.amazonaws.com/index.html

With this URL, all index documents work properly.

**Comment by laurilehmijoki** [comment]
Hello nirvdrum

Thanks for the feedback.

I just released version 2.2.4, which now prints the S3 web site URL instead of the bucket URL.

**Comment by laurilehmijoki** [comment]
By the way, did the `configure-s3-website` work as you would have liked it to work?

I welcome any feedback.

**Comment by nirvdrum** [comment]
Thanks for the quick turnaround.  configure-s3-website worked great.  My bucket was created, it was set up for web page serving, it set up index.html files.  Overall, I was extremely impressed.  I just went a bit crazy trying to figure out why not everything would load, before I stumbled upon the endpoint stuff.

I guess the only other suggestion might be to name the error file 404.html instead of error.html.  I think your name is more accurate, but it appears a lot of blogs on the topic of hosting from S3 use 404.html (probably to mirror what Rails & Apache do).

**Comment by laurilehmijoki** [comment]
Thanks for your feedback. It's nice to hear that the tool serves its purpose.

Most probably the S3 website error document will be served to the user when he requests a non-existent resource. In this sense the 404.html would be a better name for the error document. The word error, however, reflects the S3 API's intention better:

``` xml
<WebsiteConfiguration xmlns='http://s3.amazonaws.com/doc/2006-03-01/'>
    <IndexDocument>
        <Suffix>index.html</Suffix>
    </IndexDocument>
    <ErrorDocument>
        <Key>SomeErrorDocument.html</Key>
    </ErrorDocument>
</WebsiteConfiguration>
```

(Taken from the [PUT Bucket website REST API doc](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTwebsite.html)).

In addition to the "not found" case, S3 might serve the error document to the user when some other error has occurred. That's why it's better to name the document as error.html, not 404.html.
