### ISSUE TITLE
GZip not working

### ISSUE THREAD

**Issue by philipithomas** [laurilehmijoki/jekyll-s3#30]
I haven't had a chance to fully vet why GZip isn't working, but I have the GZip gem, I updated to version 2.4.1 of Jekyll-s3, and I removed all old versions of the gem. I have "gzip: true" in my gem file. The output is "No new or changed files to upload", where my impression is that it should always upload the whole site.

**Comment by alexmarchant** [comment]
I've also just run into this issue.

**Comment by philipithomas** [comment]
I think I resolved the issue by emptying my S3 bucket then running the program - it seemed to recognize the pre-GZip files as unchanged and hence did not upload them.

**Comment by alexmarchant** [comment]
Ahh, good, thanks!

**Comment by laurilehmijoki** [comment]
@philipithomas got it right.

This problem is related to the issue https://github.com/laurilehmijoki/jekyll-s3/issues/29.

You can work around the problem like this:
1. `rm _site # Empty your local Jekyll site`
2. `jekyll-s3 # Upload your empty site (note this will remove your site from S3)`
3. `jekyll # Re-generate your site`
4. `jekyll-s3 # Upload your site back to S3`
5. congrats – your gzipped Jekyll site is now on S3

The problem is that _filey-diff_, the Ruby gem responsible for deciding whether a file needs to be re-uploaded, does not yet support gzip.
