### ISSUE TITLE
max_age not respected

### ISSUE THREAD

**Issue by jeremi** [laurilehmijoki/jekyll-s3#43]
Here is my configuration : 
  max_age:
    "assets/**": 86400
    "bundles/*": 2592000
    "**": 300

but all the max_age are set to 300:
...
Upload archive.html [gzipped] [max-age=300]: Success!
Upload assets/script.js [gzipped] [max-age=300]: Success!
...
Upload bundles/f8d32d086d8f1315c47114044b281ef3.js [gzipped] [max-age=300]: Success!

I also tried to invert the config and do : 
  max_age:
    "**": 300
    "assets/**": 86400
    "bundles/*": 2592000

That did not solved it. Any idea ?

**Comment by laurilehmijoki** [comment]
Fixed in version 2.5.1.

The problem was that `upload.rb` picked the `max_age` value from the first matching setting. As a consequence, your setting `"**": 300` was applied to **all** files.

From now on, the `max_age` is picked from the longest matching selector. The commit is here: https://github.com/laurilehmijoki/jekyll-s3/commit/38e05f6f0cb6263c7986e957e027a28513f7c33a.
